[{"bug_class":"","kind":"ERROR","bug_type":"Bad_footprint","qualifier":".","severity":"LOW","visibility":"developer","line":14,"column":10,"procedure":"func","procedure_id":"func.7df4935f4a5a2865191ef74f64df8754","procedure_start_line":10,"file":"infer.c","bug_trace":[{"level":0,"filename":"infer.c","line_number":10,"column_number":1,"description":"start of procedure func()"},{"level":0,"filename":"infer.c","line_number":12,"column_number":5,"description":""},{"level":0,"filename":"infer.c","line_number":13,"column_number":5,"description":""},{"level":0,"filename":"infer.c","line_number":14,"column_number":5,"description":""}],"key":"infer.c|func|Bad_footprint","node_key":"8837ec90eed939cf91937d91e4f3c434","hash":"626a8c16d8b8cb09d941838635dcbcfe","infer_source_loc":{"file":"biabduction/Rearrange.ml","lnum":306,"cnum":38,"enum":45},"bug_type_hum":"Bad Footprint","censored_reason":""},{"bug_class":"PROVER","kind":"ERROR","bug_type":"MEMORY_LEAK","qualifier":"memory dynamically allocated by call to `malloc()` at line 13, column 16 is not reachable after line 14, column 5.","severity":"HIGH","visibility":"user","line":14,"column":5,"procedure":"func","procedure_id":"func.7df4935f4a5a2865191ef74f64df8754","procedure_start_line":10,"file":"infer.c","bug_trace":[{"level":0,"filename":"infer.c","line_number":10,"column_number":1,"description":"start of procedure func()"},{"level":0,"filename":"infer.c","line_number":12,"column_number":5,"description":""},{"level":0,"filename":"infer.c","line_number":13,"column_number":5,"description":""},{"level":0,"filename":"infer.c","line_number":14,"column_number":5,"description":""}],"key":"infer.c|func|MEMORY_LEAK","node_key":"8837ec90eed939cf91937d91e4f3c434","hash":"f9f905507a9a50e0b2da4d8f7a32b3f5","infer_source_loc":{"file":"biabduction/Abs.ml","lnum":1082,"cnum":18,"enum":25},"bug_type_hum":"Memory Leak","censored_reason":""}]
